# -*- coding: utf-8 -*-
"""Hospital DB Analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wfQ9J-jm_S5VAPaK9VqNW5jvrDO0EyUW
"""

"""
1- We have finished collecting all the data into a single table using SQL.
2- Now it's time to clean the data using Python.
"""

"""
Data Cleaning:
    - Missing Values.
    - Data Types.
    - outlires.
    - Duplacte.
"""

#===================================================================
"""
Step 1 📚 : Import Libraries.
"""
#===================================================================

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#===================================================================
"""
Step 2 📥 : Loading Data.
"""
#===================================================================

df = pd.read_csv("Fact Table.csv",
                 parse_dates=["Admit_Date","Discharge_Date","DOB","Test_Date","End_Date","Start_Date"])

# Show first 5 rows.

print("First 5 Rows:\n")
print(df.head())
print("--"*40,"\n")

# Show the size of data.

print("Shape Of Date:")
shape = df.shape
print(f"This Data Contain {shape[0]} Rows And {shape[1]} Columns.\n")
print("--"*40,"\n")


#===================================================================
"""
Step 3 🧹 : Data Cleaning.
"""
#===================================================================

# Show missing values
print("Messing Values Before Cleaning:\n")
print(df.isnull().sum())
print("\nDrop missing Values.")
df=df.dropna()
print("\nMissing Values After Cleaning:\n")
print("\n",df.isnull().sum())
print(df.shape)
print("--"*40,"\n")

# Convert Columns that have a wrong datatype.

print("Data Types Before Convert:\n")
print(df.dtypes)
Numeric_columns = ["Staff_ID","Diag_ID","Lab_ID","Med_ID","Proc_ID"]
df[Numeric_columns] = df[Numeric_columns].astype("Int64")
print("Data Types After Convert:\n")
print(df.dtypes)
print("--"*40,"\n")

# Identify numeric columns automatically
numeric_cols = df.select_dtypes(include=['int64', 'float64','Int64']).columns

# Find Outliers.

def remove_outliers_iqr(df, column):
    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    df_clean = df[(df[column] >= lower) & (df[column] <= upper)]
    return df_clean

print("\nThe outliers have been verified:\n")

for col in numeric_cols:
    print(f"Cleaning outliers in: {col}")
    df_cleaning = remove_outliers_iqr(df, col)

print(df_cleaning.shape)
print("\n","--"*40)

# Find Dublicated Values
print("\n Dublicated Values:\n")
print(df_cleaning.duplicated().sum())

df_cleaning.to_csv("fact_table.csv", index=False)

